# SPDX-License-Identifier: GPL-3.0-or-later
"""The binding key-name vocabulary: ``KEY_*``/``BTN_*`` names and Linux UAPI codes.

``hotkey.binding`` is written with these names on every platform (see
:class:`stenographer.lib.platform.key_table.KeyTable`), so the vocabulary itself is core
data rather than a host capability -- a provider with no evdev can still parse
and render a binding. Pure and stdlib-only.

The data lives in ``assets/keycodes.toml``, GENERATED by
``scripts/gen_keycodes.py`` from ``evdev.ecodes``; do not edit it by hand. This
module only loads that file once at import.
``tests/platform/linux/test_keycodes_drift.py`` proves it still matches."""

from __future__ import annotations

import tomllib
from collections.abc import Mapping
from importlib.resources import files
from types import MappingProxyType
from typing import Any, Final


def _load_data() -> dict[str, Any]:
    """Parse the generated data file (``[codes]`` and ``[names]`` tables)."""
    asset = files("stenographer").joinpath("assets", "keycodes.toml")
    return tomllib.loads(asset.read_text(encoding="utf-8"))


_DATA = _load_data()


KEY_CODES: Final[Mapping[str, int]] = MappingProxyType(dict(_DATA["codes"]))


CODE_NAMES: Final[Mapping[int, str]] = MappingProxyType(
    {int(code): name for code, name in _DATA["names"].items()}
)
