# SPDX-License-Identifier: GPL-3.0-or-later
"""Regenerate ``stenographer.keycodes`` from the installed ``evdev.ecodes``.

The binding vocabulary (``KEY_*``/``BTN_*`` names and their Linux UAPI codes)
is static data, not a host capability, so it belongs in the core rather than
behind the platform boundary. This script emits it; the Linux-only drift test
(``tests/platform/linux/test_keycodes_drift.py``) proves the emitted table
still agrees with evdev.

Usage (Linux, with the dev venv, from the repo root)::

    .venv/bin/python scripts/gen_keycodes.py            # rewrite the module
    .venv/bin/python scripts/gen_keycodes.py --check    # fail if out of date
"""

from __future__ import annotations

import argparse
import difflib
from pathlib import Path

_TARGET = Path(__file__).resolve().parents[1] / "src/stenographer/keycodes.py"
_PREFIXES = ("KEY_", "BTN_")

_HEADER = '''# SPDX-License-Identifier: GPL-3.0-or-later
"""The binding key-name vocabulary: ``KEY_*``/``BTN_*`` names and Linux UAPI codes.

``hotkey.binding`` is written with these names on every platform (see
:class:`stenographer.platform.base.KeyTable`), so the vocabulary itself is core
data rather than a host capability -- a provider with no evdev can still parse
and render a binding. Pure and stdlib-only.

GENERATED by ``scripts/gen_keycodes.py`` from ``evdev.ecodes``; do not edit by
hand. ``tests/platform/linux/test_keycodes_drift.py`` proves it still matches.
"""

from __future__ import annotations

from collections.abc import Mapping
from types import MappingProxyType
from typing import Final

KEY_CODES: Final[Mapping[str, int]] = MappingProxyType(
    {
'''

_MIDDLE = '''    }
)
"""Every ``KEY_*``/``BTN_*`` name to its code (aliases included)."""

CODE_NAMES: Final[Mapping[int, str]] = MappingProxyType(
    {
'''

_FOOTER = '''    }
)
"""Each code to its canonical name (evdev's first spelling when aliased)."""


class StaticKeyTable:
    """:class:`~stenographer.platform.base.KeyTable` over the generated table."""

    def code(self, name: str) -> int:
        return KEY_CODES[name]

    def name(self, code: int) -> str | None:
        return CODE_NAMES.get(code)
'''


def _tables() -> tuple[dict[str, int], dict[int, str]]:
    import evdev

    codes = {
        name: value
        for name, value in evdev.ecodes.ecodes.items()
        if name.startswith(_PREFIXES) and isinstance(value, int)
    }
    names: dict[int, str] = {}
    for code, spelling in evdev.ecodes.KEY.items():
        canonical = spelling[0] if isinstance(spelling, list | tuple) else spelling
        if isinstance(canonical, str) and canonical.startswith(_PREFIXES):
            names[code] = canonical
    return codes, names


def render() -> str:
    """The full text of the generated module."""
    codes, names = _tables()
    code_lines = "".join(f'        "{n}": {c},\n' for n, c in sorted(codes.items()))
    name_lines = "".join(f'        {c}: "{n}",\n' for c, n in sorted(names.items()))
    return _HEADER + code_lines + _MIDDLE + name_lines + _FOOTER


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if the module is stale")
    args = parser.parse_args()

    generated = render()
    current = _TARGET.read_text(encoding="utf-8") if _TARGET.exists() else ""
    if generated == current:
        print(f"keycodes up to date: {_TARGET}")
        return
    if args.check:
        diff = difflib.unified_diff(
            current.splitlines(keepends=True),
            generated.splitlines(keepends=True),
            fromfile=str(_TARGET),
            tofile="generated",
        )
        raise SystemExit("".join(diff) + f"\nstale: rerun {Path(__file__).name}")
    _TARGET.write_text(generated, encoding="utf-8")
    print(f"wrote {_TARGET}")


if __name__ == "__main__":
    main()
